"""Building blocks for panel artwork: fonts as outlines, colour themes, the Panel class and the shared knob and
button graphics. Each module's panel lives in panels/<slug>.py and is built from these; panel.py writes them all.

Every panel carries a hidden "components" layer in the SDK helper.py convention (red params, green inputs, blue
outputs, magenta lights, yellow custom widgets), which the C++ side reads back at runtime to place each widget (see
PanelLayout in src/ui.hpp). Labels are converted to outlines, since Rack's SVG renderer ignores <text>.
"""
import json
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = json.loads((ROOT / 'plugin.json').read_text())


def num(v):
    return f'{v:.3f}'.rstrip('0').rstrip('.')


def mix(a, b, t):
    """Blend two #RRGGBB colours."""
    pa, pb = bytes.fromhex(a[1:]), bytes.fromhex(b[1:])
    return '#' + bytes(round(x + (y - x) * t) for x, y in zip(pa, pb)).hex().upper()


class Font:
    def __init__(self, path):
        tt = TTFont(path)
        self.glyphs, self.cmap = tt.getGlyphSet(), tt.getBestCmap()
        self.upem = tt['head'].unitsPerEm
        self.cap = tt['OS/2'].sCapHeight / self.upem

    def width(self, text, size):
        return sum(self.glyphs[self.cmap[ord(c)]].width for c in text) * size / self.upem

    def path(self, text, x, y, size, anchor='middle'):
        """Outlines of `text` as SVG path data, with its cap height centred on `y`."""
        x -= {'start': 0, 'middle': 0.5, 'end': 1}[anchor] * self.width(text, size)
        y += self.cap * size / 2
        s = size / self.upem
        pen = SVGPathPen(self.glyphs, num)
        for c in text:
            glyph = self.glyphs[self.cmap[ord(c)]]
            glyph.draw(TransformPen(pen, (s, 0, 0, -s, x, y)))
            x += glyph.width * s
        return pen.getCommands()


NUNITO = Font(ROOT / 'res-src/fonts/Nunito-Bold.ttf')

# Colour roles, filled into the artwork per theme. Rack picks the dark panel when the user prefers dark panels.
THEMES = {
    '': dict(panel='#ECEBE8', ink='#3A3A3C', title='#2B2B2D', line='#C4C2BE', footer='#A9A8A4',
             bezel='#2F3032', glass='#030304', box='#2D2E31', box_ink='#E4E3E0'),
    '-dark': dict(panel='#2B2C2E', ink='#C9C8C4', title='#ECEBE8', line='#4A4B50', footer='#707175',
                  bezel='#141516', glass='#030304', box='#1C1D1F', box_ink='#C9C8C4'),
}
PASTELS = dict(yellow='#F4D394', green='#C4DDAB', teal='#A4D9D5', lavender='#B7C0F2',
               salmon='#F5B3A6', cyan='#ABE6F5', pink='#F7BDD6')
COMPONENT_COLORS = dict(PARAM='#FF0000', INPUT='#00FF00', OUTPUT='#0000FF', LIGHT='#FF00FF', WIDGET='#FFFF00')

HP = 5.08
KNOB_R, SOFT_R, BUTTON_R = 5.5, 3.75, 3.6  # radii (mm) of the components generated below
LABEL = 2.6  # label font size (mm)


def document(width, height, body):
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by res-src/panel.py -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" '
            f'width="{num(width)}mm" height="{num(height)}mm" viewBox="0 0 {num(width)} {num(height)}">\n{body}\n</svg>\n')


class Panel:
    """Artwork with {role} colour placeholders, plus the components layer that positions the widgets."""

    def __init__(self, width, height):
        self.width, self.height = width, height
        self.art, self.components = [], []

    def rect(self, x, y, w, h, r, fill):
        self.art.append(f'<rect x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}" rx="{num(r)}" fill="{{{fill}}}"/>')

    def line(self, x1, y1, x2, y2, stroke='line', width=0.35):
        self.art.append(f'<path d="M{num(x1)} {num(y1)}L{num(x2)} {num(y2)}" stroke="{{{stroke}}}" stroke-width="{num(width)}"/>')

    def text(self, s, x, y, size=LABEL, fill='ink', anchor='middle'):
        self.art.append(f'<path d="{NUNITO.path(s, x, y, size, anchor)}" fill="{{{fill}}}"/>')

    def place(self, name, x, y, w=0, h=0):
        """Marks where the widget for C++ enum `name` (FREQ_PARAM, OUT_LIGHT, SCREEN_WIDGET...) goes.
        The suffix picks the helper.py colour; a size makes it a rectangle instead of a centre point."""
        kind = name.rsplit('_', 1)[1]
        attrs = f'id="{name}" inkscape:label="{name[:-len(kind) - 1].lower()}" fill="{COMPONENT_COLORS[kind]}"'
        if w:
            self.components.append(f'<rect {attrs} x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}"/>')
        else:
            self.components.append(f'<circle {attrs} cx="{num(x)}" cy="{num(y)}" r="1"/>')

    def title(self, slug):
        """The module's name from plugin.json at the top, the brand at the bottom between the screws."""
        name = next(m['name'] for m in MANIFEST['modules'] if m['slug'] == slug)
        self.text(name.lower(), self.width / 2, 6.3, size=5.2, fill='title')
        self.text(MANIFEST['brand'], self.width / 2, self.height - 2.54, size=2.3, fill='footer')

    def svg(self, theme):
        art = '\n    '.join(self.art).format(**theme)
        components = '\n    '.join(self.components)
        return document(self.width, self.height,
                        f'  <g id="artwork" inkscape:groupmode="layer" inkscape:label="artwork">\n    {art}\n  </g>\n'
                        f'  <g id="components" inkscape:groupmode="layer" inkscape:label="components" style="display:none">\n'
                        f'    {components}\n  </g>')


def knob_bg(r, cap):
    """Static part of a knob: dark skirt and coloured cap, lit from the top left. The cap's id lets the
    C++ side read its colour, so a knob's screen readout always matches the knob."""
    c = num(r)
    return document(2 * r, 2 * r, f'''  <defs>
    <linearGradient id="skirt" x1="0" y1="0" x2="0" y2="{num(2 * r)}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#4A4A50"/><stop offset="1" stop-color="#17171A"/>
    </linearGradient>
    <radialGradient id="shine" cx="{num(r * 0.8)}" cy="{num(r * 0.7)}" r="{num(r * 0.7)}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.4"/><stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <circle cx="{c}" cy="{c}" r="{c}" fill="url(#skirt)"/>
  <circle id="cap" cx="{c}" cy="{c}" r="{num(r * 0.8)}" fill="{cap}"/>
  <circle cx="{c}" cy="{c}" r="{num(r * 0.68)}" fill="{mix(cap, '#FFFFFF', 0.15)}"/>
  <circle cx="{c}" cy="{c}" r="{num(r * 0.68)}" fill="url(#shine)"/>''')


def knob_pointer(r, length, width):
    """Rotating part of a knob: just the pointer, so the lighting on the static part stays put."""
    c = num(r)
    return document(2 * r, 2 * r, f'  <path d="M{c} {num(r * (1 - length[0]))}V{num(r * (1 - length[1]))}" '
                                  f'stroke="#202023" stroke-width="{num(width)}" stroke-linecap="round"/>')


def button(r, fill):
    c = num(r)
    return document(2 * r, 2 * r, f'  <circle cx="{c}" cy="{c}" r="{num(r - 0.35)}" fill="{fill}" stroke="#141416" stroke-width="0.6"/>')


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(path.relative_to(ROOT))
