#pragma once
#include "plugin.hpp"
#include <cstring>

// Reusable panel parts. The graphics live in res/components and are generated by res-src/panel.py.


/** The shape with this id in an SVG, or null. */
inline NSVGshape* findShape(const std::shared_ptr<window::Svg>& svg, const char* id) {
	if (svg && svg->handle)
		for (NSVGshape* shape = svg->handle->shapes; shape; shape = shape->next)
			if (!std::strcmp(shape->id, id))
				return shape;
	return nullptr;
}

/** Fill colour of the shape with this id, so code can match colours in the artwork. */
inline NVGcolor svgFill(const std::shared_ptr<window::Svg>& svg, const char* id, NVGcolor fallback) {
	NSVGshape* shape = findShape(svg, id);
	if (!shape || shape->fill.type != NSVG_PAINT_COLOR)
		return fallback;
	uint32_t c = shape->fill.color; // nanosvg packs colours as 0xAABBGGRR
	return nvgRGBA(c & 0xff, (c >> 8) & 0xff, (c >> 16) & 0xff, c >> 24);
}


/** Widget positions, read from the hidden "components" layer of a panel SVG.

Each shape on that layer is named (its id) after the enum value of the widget that goes there:
FREQ_PARAM, OUT_LIGHT, SCREEN_WIDGET... This is the SDK's helper.py convention, so the same panel still
works with `helper.py createmodule`. Reading positions at runtime means the panel is the only place the
layout is written down: move a component in Inkscape or res-src/panel.py and the widget follows. */
struct PanelLayout {
	std::shared_ptr<window::Svg> svg;

	explicit PanelLayout(const std::string& path) : svg(window::Svg::load(path)) {}

	/** Bounding box in px, or an empty box at the origin (and a warning in the log) if the panel lacks the component. */
	math::Rect box(const char* id) const {
		NSVGshape* shape = findShape(svg, id);
		if (!shape) {
			WARN("Panel has no component named %s", id);
			return math::Rect();
		}
		return math::Rect::fromMinMax(math::Vec(shape->bounds[0], shape->bounds[1]), math::Vec(shape->bounds[2], shape->bounds[3]));
	}

	math::Vec center(const char* id) const {
		return box(id).getCenter();
	}
};


enum class Pastel { Yellow, Green, Teal, Lavender, Salmon, Cyan, Pink };

/** Large knob with a pastel cap, for a module's main parameters.

Like Rack's RoundKnob, only the pointer rotates; the cap and its highlight stay put so the lighting is
consistent. The cap is the shape with id "cap" in the background graphic, which is how a Screen readout
finds the knob's colour. */
template <Pastel P>
struct PastelKnob : RoundKnob {
	PastelKnob() {
		static const char* const colors[] = {"yellow", "green", "teal", "lavender", "salmon", "cyan", "pink"};
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/components/PastelKnob.svg")));
		bg->setSvg(Svg::load(asset::plugin(pluginInstance, std::string("res/components/PastelKnob_bg-") + colors[(int) P] + ".svg")));
	}
};

/** Smaller white knob, for the soft keys beside a screen. */
struct SoftKnob : RoundKnob {
	SoftKnob() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/components/SoftKnob.svg")));
		bg->setSvg(Svg::load(asset::plugin(pluginInstance, "res/components/SoftKnob_bg.svg")));
	}
};

/** Round momentary push button: one frame per param value, and `momentary` springs it back on release. */
struct PushButton : app::SvgSwitch {
	PushButton() {
		momentary = true;
		addFrame(Svg::load(asset::plugin(pluginInstance, "res/components/PushButton_0.svg")));
		addFrame(Svg::load(asset::plugin(pluginInstance, "res/components/PushButton_1.svg")));
	}
};

/* your components here */
